In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [ ]:
b = np.array([[9,8,7],[5,3,7]])
print(b)

[[9 8 7]
 [5 3 7]]


In [ ]:
a.ndim

1

In [ ]:
b.ndim


2

In [ ]:
b.shape

(2, 3)

In [ ]:
a.dtype

dtype('int16')

In [ ]:
a.nbytes

12

In [ ]:
a = np.array([[2,4,7,4,2,5,1],[2,8,9,3,6,1,5]])
print(a)

[[2 4 7 4 2 5 1]
 [2 8 9 3 6 1 5]]


In [ ]:
a[1,6]

5

In [ ]:
a[0,:]

array([2, 4, 7, 4, 2, 5, 1])

In [ ]:
a[:,2]

array([7, 9])

In [ ]:
a[0,1:6:2]

array([4, 4, 5])

In [ ]:
a[:,2]=[1,2]
print(a)

[[2 4 1 4 2 5 1]
 [2 8 2 3 6 1 5]]


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
b[:,1,:]=[[9,9],[8,8]]

In [ ]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,3,2), dtype ='int64')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [ ]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.52085847, 0.32447592, 0.27506487, 0.4819055 , 0.01754972,
        0.611991  , 0.12132814],
       [0.42695857, 0.22317446, 0.94387864, 0.35337526, 0.5740794 ,
        0.06181468, 0.14778792]])

In [ ]:
np.random.randint(30,size=(3,3))

array([[ 2, 10,  3],
       [24,  3,  0],
       [10, 14, 18]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z= np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a =np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c =np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.max(stats)

6

In [ ]:
np.sum(stats,axis=0)

array([5, 7, 9])